<?php
/**
 * Created by JiangJiaCai.
 * User: Administrator
 * Date: 2017/11/20 0020
 * Time: 15:10
 */

namespace com_jjcbs\cases\test;


use PHPUnit\Framework\TestCase;

class AnnotationParseTest extends TestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}