<?php
/**
 * Created by JiangJiaCai.
 * User: Administrator
 * Date: 2017/8/24 0024
 * Time: 15:46
 */

namespace com_jjcbs\cases\test;


use com_jjcbs\lib\ServiceFactory;
use com_jjcbs\service\AnnotationServiceImpl;
use PHPUnit\Framework\TestCase;

class AnnotationServiceImplTest extends TestCase
{
    private $annoationService = null;
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->annoationService = ServiceFactory::getInstance(AnnotationServiceImpl::class);
    }

    public function testExec(){
        $this->annoationService->setSrcClass('com_jjcbs\test\resource\TestOutPutAnnotation');
        $arr = $this->annoationService->exec();
        $this->assertNotEmpty($arr);
    }
}